query MyQuery($numberOfLists: Int, $numberOfBooksPerPage: Int, $skipBook: Int) {
  all_books_list(limit: $numberOfLists) {
    items {
      book_listsConnection(limit: $numberOfBooksPerPage, skip: $skipBook) {
        edges {
          node {
            ... on Book {
              title
              author
              description
              imageConnection {
                edges {
                  node {
                    url(transform: { height: "140", quality: 50, width: "110" })
                    title
                  }
                }
              }
              system {
                uid
              }
              pages
            }
          }
        }
        totalCount
      }
    }
  }
}
